### ISSUE TITLE
Unable to import modules when running in server in docker.

### ISSUE THREAD

**Issue by benjaminlgur** [jina-ai/dalle-flow#39]
Looks like I am unable to import certain modules such as `ERROR  dalle/rep-0@31 ImportError('can not import module     [06/14/22 09:35:53]                                                                             from /dalle/dalle-flow/executors/dalle/dm_helper.py')                                                                                                 `                                   

Gist with master paste: https://gist.github.com/benjaminlgur/ff52e3cc87d9edfb74c4bb26d8fc82d4

Also am I correct that to access the docker container I use 'grpc://0.0.0.0:51005' as the server_url?

**Comment by Pathos14489** [comment]
Running into this issue, and not running out of VRAM. It's returning
```
AttributeError: module 'jaxlib.pocketfft' has no                         
       attribute 'pocketfft'
```

**Comment by matrach** [comment]
@Pathos14489 

In my case, `pip install -r requirements.txt` from the [Dockerfile](https://github.com/jina-ai/dalle-flow/blob/main/Dockerfile#L34), upon seeing
```
jax[cuda] -f https://storage.googleapis.com/jax-releases/jax_releases.html
```
 installs `jax==0.2.X`, because for some reason `jax[cuda]` fails to install with `jax >= 3`.

Replacing it with the version from the Dockerfile or commenting this line, should resolve the problem when building the image
```
jax==0.3.13 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

(I've also changed the corresponding line in Dockerfile to: ` pip install "jax==0.3.13" "jaxlib[cuda11_cudnn82]==0.3.10" -f https://storage.googleapis.com/jax-releases/jax_releases.html `)

Just keep in mind, that this probably breaks  barebone installation.

**Comment by dhungtrinh** [comment]
> The .cache issue appears to be unrelated to this. Even when you avoid the .cache access issue, it will still fail to import the module from dm_helper.py
> 
> I'm getting that error, i.e., `ImportError: can not import module from /dalle/dalle-flow/executors/dalle/dm_helper.py` despite that file existing in the container (i.e., by using `docker exec -it <container> bash` and navigating to the directory).
> 
> Edit: looking back through the logs, I realize I was running out of memory (running out of an instance with 16GB of memory). Using a larger instance avoided this problem.

The resolution of running on a larger instance does not work. I am using Nvidia Tesla A100 on GCP, with a CUDA 11.3 (not 11.6) by pulling the prebuilt docker.

**Comment by dhungtrinh** [comment]
.

**Comment by nathanmargaglio** [comment]
> The resolution of running on a larger instance does not work. I am using Nvidia Tesla A100 on GCP, with a CUDA 11.3 (not 11.6) by pulling the prebuilt docker.

So I actually just sent this message to someone else regarding this:

> I faced a number of different issues with setting up DALLE-Flow in AWS, and the issue you're mentioning (can't import dm_helper.py) is actually misleading, as it threw that error when different things went wrong. You'll have to look back through the trace to figure what the "real" issue is.

> If I recall correctly, using the a Deep Learning AMI running Amazon Linux 2 that had CUDA 11.6 was what ended up working for me. But when I try to start the Docker image using this AMI, I'd see the error you see (can't import dm_helper.py). Looking through the trace, I noticed it said there was a MemoryError. Changing my instance from a g5.xlarge to a g5.2xlarge did the trick (although you might be able to get away with sufficient swap space).

> So, basically, if it's a memory error, you should be able to find it in the trace then adjust your memory accordingly (16GB is not enough, but 32GB is). If it's not a memory issue, then it may be an issue with your environment, in which case good luck lol

Now, it's been a little bit since I set it up so my memory is fuzzy, but I do remember trying to set this up using an AMI with CUDA 11.3 installed and facing different issues than the memory error. I only found success with instances having CUDA 11.6, so maybe try updating your CUDA.

And like I said, try looking back through/more closely at the trace when you get an error. It can be difficult to parse, but I did notice that the "can't import dm_helper.py" is a bit of a red herring.

**Comment by dhungtrinh** [comment]
> Looks like I am unable to import certain modules such as `ERROR dalle/rep-0@31 ImportError('can not import module [06/14/22 09:35:53] from /dalle/dalle-flow/executors/dalle/dm_helper.py') `
> 
> Gist with master paste: https://gist.github.com/benjaminlgur/ff52e3cc87d9edfb74c4bb26d8fc82d4
> 
> Also am I correct that to access the docker container I use 'grpc://0.0.0.0:51005' as the server_url?

Ok, I managed to get this to work with the guidance of nathanmargaglio. I will present one way to get this to work end-to-end so that you have at least one verified pathway to get Jina to work. Note, since we are using a pre-built AMI on AWS this method may not work in the long-term future. In any case, these steps work as of 06/14/22 09:35:00

Requirements
- Amazon AWS

1. Set up a g5.2xlarge instance on Amazon AWS. This is easy, and you should not be discouraged. You need to request an increase in the service quote to 8 vCPUs to launch it. You need to install this AMI from AWS, 'Deep Learning AMI GPU PyTorch 1.11.0 (Amazon Linux 2) 20220328' which has an identifier `ami-023d5aa1ee956059c`. I had EBS 300gb gp3 for the root disk, and g5.2xlarge comes with a default instance store volume of 450gb. I also added an EFS file system. 
2. To access this instance did I ssh by wsl on Windows 10 through VsCode. To ssh do you need a private key generated upon the creation of your EC2 instance, which was automatically downloaded to your local machine. You will get an error message using the raw .pem and will need to change the permissions related to this file with chmod 0400. However, to do this with wsl, windows 10 and vscode do you need to change the wsl.conf in /etc/wsl.conf. Just search the error you get up to find the right Stackoverflow
3. So after you have ssh into the instance will you see that the CUDA version installed is 11.5. That is actually a display bug, as you can check with the command 'nvidia-smi' that the CUDA version installed is indeed 11.6. 
4. You will also be prompted to 'sudo yum update' at the first launch, so do that, as it won't cause issues. 
5. Then you need to download the docker image of Dalle-flow with this command. docker pull jinaai/dalle-flow:latest
6. After this I tried to docker run, and got this error 'docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]. ERRO[0002] error waiting for container: context canceled' I resolved this by only using this command. 'sudo systemctl restart docker'. 
7. Now, the source of your bug wrt being unable to import '/dalle/dalle-flow/executors/dalle/dm_helper.py' I have found comes from the faulty implementation of their provided command 'docker run -p 51005:51005 -v $HOME/.cache:/home/dalle/.cache --gpus all jinaai/dalle-flow' instead use this command 'docker run -p 51005:51005 --gpus all jinaai/dalle-flow'
8. To access the server using Google Colab, change your Security Group for your AWS instance to give access to the right TCP calls. I tested that it works if you allows 'ALL TCP' to have access to your instance, but this is definitely not recommended. I just did it to see how I could connect the Google Colab provided by Jina AI to this EC2 instance. You definitely do not want this as a permanent solution as bots can snipe your compute resources and expose security risks. Anyhow, if you just for the moment add a rule to the right security group for your instance, that alllows for ALL TCP, then you can simply change the 'server-url' insuide the provided Google Colab in Github, from 'server_url = 'grpc://dalle-flow.jina.ai:51005' to server_url = 'grpc://[YOUR-AWS-PUBLIC-IP]:51005'

DONE.

**Comment by delgermurun** [comment]
I believe this issue has been resolved. Feel free to reopen if the problem occurs again.
