### ISSUE TITLE
Installing locally taking mysteriously long

### ISSUE THREAD

**Issue by ArtsyMedia** [jina-ai/dalle-flow#51]
I am having a problem with the final code in the installation process:

`jina flow --uses flow.yml`

After running that in the console, the progress meter makes its way up to 5/6 before stalling for way too long. I've attached an image of what it looks like for me right now. Any way to fix this? There are no console errors and I am on a Mac with an M1 chip if that helps.

<img width="568" alt="Screen Shot 2022-06-24 at 5 16 37 PM" src="https://user-images.githubusercontent.com/79327876/175672750-143c9f32-5d7b-4c3f-b8fc-7eeabdc41007.png">

Above you can see that It's taken 37 minutes on just the 5th step alone.

**Comment by hanxiao** [comment]
bug of jax, try you run this simple code

```python
from jax import grad
import jax.numpy as jnp

def tanh(x):  # Define a function
  y = jnp.exp(-2.0 * x)
  return (1.0 - y) / (1.0 + y)

grad_tanh = grad(tanh)  # Obtain its gradient function
print(grad_tanh(1.0))   # Evaluate it at x = 1.0
# prints 0.4199743
```

 i believe it will seg-fault

**Comment by hanxiao** [comment]
That's the reason, you build it on M1, so by default `docker build` build it as `arm/aarch64`, whereas JAX does not support `aarch64`. You should run `docker build --platform linux/amd64`. 

Notice, it will be very slow because you are trying to build cross-arch artifact on M1. It will be much faster if you can find an Intel 64-bit CPU machine to build it. I use M1 by myself but I rarely cross-arch build large image.

Also this issue is beyond DALLE-flow, it is the docker usage on M1, please consult StackOverflow. 

Closing issue, if any further question please create new issue, thanks!
